
- name: Set environment code
  set_fact:
    env_code: "{{ env_map[environment] }}"

- name: Set simple hostname (TEMP FIX)
  set_fact:
    hostname: "TEST-{{ env_code }}-01"

- name: Debug hostname
  debug:
    var: hostname
