# group_vars/all.yml
vcenter_hostname: "labvca50.nordsoncorp.local"
vcenter_username: "admin.shaffer@nordsoncorp.local"
vcenter_password: "Johnathan0730-!"

environments:

  dev:
    datacenter: "LAB Datacenter"
    cluster: "LAB Cluster"
    datastore: "LABVMW_DATASTORE"
    network: "LABServerPortGroup"
    folder: "/LAB Datacenter/vm"
    cpu: 2
    memory: 4096
    disk: 160

  prod:
    datacenter: "dc-prod"
    cluster: "prod-cluster"
    datastore: "prod-ds"
    network: "vlan-prod"
    folder: "/vm/prod"
    cpu: 2
    memory: 8192
    disk: 200
