- name: TEST VERSION CHECK
  debug:
    msg: "THIS IS NEW CODE VERSION 3"

- name: Self-Service Provisioning
  hosts: localhost
  gather_facts: false

  roles:
    - naming_authority
    - vm_provision
